module.exports = {
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testPathIgnorePatterns: ['<rootDir>/.next/', '<rootDir>/node_modules/', '/__utils__/'],
  testEnvironment: 'jsdom',
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90,
    },
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    'src/**/*.tsx',
    '!src/lib/mongoClient.ts',
    '!src/utils/wordUtils.ts',
    '!src/context/*.tsx',
    '!src/components/select/Select.tsx',
    '!src/components/error/Error.tsx',
    '!src/components/review/Review.tsx',
    '!src/components/fireworks/Fireworks.tsx',
    '!src/app/test/page.tsx',
    '!src/app/settingsWords/page.tsx',
    '!src/app/settingsAccount/page.tsx',
    '!src/app/settingsWords/page.tsx',
    '!src/app/settings/page.tsx',
    '!src/app/layout.tsx',
    '!src/app/page.tsx',
    '!src/middleware.ts',
  ],
};
